### ISSUE TITLE
Client doesn't keep tracking league adverts after restart.

### ISSUE THREAD

**Issue by pjithorpe** [pjithorpe/rugby-royale#12]
When the discord bot is stopped or crashes, it loses track of the active league advert messages. These are only stored in memory, and instead need to be persisted somewhere.

- [ ] Decide how to store league advert message tracking info.

- [ ] Client should save trackers on the fly / on shutdown.

- [ ] Client should reload saved trackers during initialisation.
